apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: mongo-pvc 
spec: 
  volumeName: mongo-pv 
  accessModes: 
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" 